export const ACTIONS = {
    SET_FILE_NAME: "set file name",
    SET_TAB: "set tab",
    PICKUP_PHONE: "pick up phone",
    END_PHONE: "end phone",
    SUMMARIZE: "Summarize",
    FETCH_CLIENT_DATA: "fetch client data",
    CLEAR_CLIENT_DATA: "clear client data",
    CREATE_CLIENT: "create client",
    STORE_SUMMARY: "store summary",
    FETCH_SUMMARY_LIST: "fetch summary list",
    REPORT_ERROR: "report error",
    LOADING_STATUS: "loading status",
    FETCH_AUDIO_URL:"fetch audio url",
}